name: Template rename

on:
  workflow_dispatch:

permissions: write-all

jobs:
  get-context:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      changes: ${{ steps.result.outputs.changes }}
      changes-shell: ${{ steps.result.outputs.changes-shell }}
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

  rename:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.rename.outputs.commit-hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rename project
        uses: kota65535/github-template-rename-action@main
        id: rename
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: '[skip ci] rename'
          paths-ignore: |
            **/*.jar

  reset-versions:
    runs-on: ubuntu-latest
    needs:
      - rename
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Configure git
        uses: kota65535/github-git-config-action@v1
        with:
          user.name: Tomohiko Ozawa           # Set user.name
          user.email: kota65535@gmail.com     # Set user.email
      - name: Commit & push
        run: |
          set -x
          echo "aaa" > a.txt
          git add .
          if ! git diff-index --cached --quiet HEAD; then
            git commit -m 'revert versions'
            git push origin HEAD
          fi
